module.exports = {
	BACKGROUNDS: ['sand', 'calm_sand', 'gray_sand', 'night_sand'],
	COLORS: ['GREEN', 'BLUE', 'PINK', 'GOLD'],
	DEATH_TICKS: 2,
	DIRECTIONS: ['RIGHT', 'LEFT', 'UP', 'DOWN'],
	GOAL_SCORE: 40,
	GRID_COLUMNS: 40,
	GRID_ROWS: 30,
	LOOP_REPEAT_INTERVAL: 80,
	MAX_PLAYERS: 4,
	MINE_SPAWN_DISTANCE: 2,
	NEW_BODY_LENGTH: 8,
	SNAKE_LOADING_IMAGE: 'images/venomous_brown_tree_snake.jpg',
	TICKS_UNTIL_RESET: 90,
}
